### PR TITLE
Support for Rails 8.0

### PR DESCRIPTION
**Pull request by frederikspang**
Use the attr_reader that is currently aliased to `@model`. 

`@klass` has been renamed as of Rails 8.0 to `@model` but the reader method has been kept.

### CODE REVIEW

**Comment by glebm** [comment]
Since Travis isn't free for OSS anymore, this repo needs to be migrated to GitHub Actions.
Merging for now but it'd be great if someone submitted a PR migrating this to GHA.

**Comment by glebm** [comment]
Note that if we drop support for old rails versions, this line needs to be updated as well

https://github.com/brianhempel/active_record_union/blob/87cc337ea5137ee77b2bc6f5f1ea8745279d39a9/active_record_union.gemspec#L21

**Comment by frederikspang** [comment]
Agreed! Let's go for 7.0+, as 6.1 has ended about a week ago.
I can give GH Actions a go if wanted.

**Comment by timdiggins** [comment]
@frederikspang this commit is missing the gemfiles you mention in this commit (I think they were just missing from your commit) - will be needed by the gh actions

**Comment by frederikspang** [comment]
> @frederikspang this commit is missing the gemfiles you mention in this commit (I think they were just missing from your commit) - will be needed by the gh actions

@timdiggins You're absolutely right. That's my bad! I'll fix it with the GH Actions PR when I have a moment!

**Comment by timdiggins** [comment]
No problem. I've worked out what they should be and I've almost got the GH actions working : https://github.com/thredded/active_record_union/actions/ (based on your branch)

**Comment by timdiggins** [comment]
I have brought back running tests for 6.0 in my GH actions branch, because it's the only one which I can get actually green out of the box (6.1+ have something breaking, and it's happening both on CI and locally) - 5.2 breaks on CI, so let's drop that.

**Comment by yush-nh** [comment]
Hi. 
I would like to use this gem with Rails 8.0. Do you have an estimated release for the next version that supports Rails 8.0?

Thank you for your hard work on this project!

**Comment by frederikspang** [comment]
> I have brought back running tests for 6.0 in my GH actions branch, because it's the only one which I can get actually green out of the box (6.1+ have something breaking, and it's happening both on CI and locally) - 5.2 breaks on CI, so let's drop that.

Am I correct in assuming this is solved in https://github.com/brianhempel/active_record_union/pull/37 ?
@timdiggins

**Comment by timdiggins** [comment]
@frederikspang correct - I've dropped 5.2 and everything 6.0 → 8.0 inclusive is green

**Comment by frederikspang** [comment]
> @frederikspang correct - I've dropped 5.2 and everything 6.0 → 8.0 inclusive is green

Great!

**Pull request merged**
