### PR TITLE
Added #union_all

### PR DESCRIPTION
**Pull request by pic**
added support for "UNION ALL"

### CODE REVIEW

**Comment by brianhempel** [comment]
What's your use case for `UNION ALL`?

**Comment by pic** [comment]
as far as I know, UNION removes duplicates, UNION ALL does not, so it is
faster.
That is convenient when you do not need to remove duplicates ore where you
already not that the two tables have an empty intersection

**Comment by brianhempel** [comment]
Do you have a use for it? (What inspired you to make the PR?)

**Comment by pic** [comment]
yes, I want to use it in a query I have which is quite slow and I hope I
can improve the speed with UNION ALL. Moreover, in my case, it is totally
fine to UNION ALL because the two tables should not have duplicates.

Sorry but I do not have numbers about difference in speed in my case yet,
it is a work in progress.
As soon as I have time I want to bundle with my fork and try the same query
with union_all and compare.

To be completely honest, I do not think that UNION ALL will be enough to
solve my speed problem, so in the end I will have to change something else,
I think.

**Comment by brianhempel** [comment]
Thanks. I think I am in favor of adding it. Bug me in a week if I haven't merged this.

**Comment by pic** [comment]
FYI: in my case UNION ALL was really useful.

I have this table, it is not big, just 20k records, but I have a complex
query on it, something like:
(a JOIN b JOIN c) union (a JOIN b JOIN c) with various WHERE / ORDER .

Using UNION it used to take 4 seconds to run, with UNION ALL it is down 0.1
second.

Best regards

**Comment by brianhempel** [comment]
[Version 1.1.0](https://rubygems.org/gems/active_record_union) is now available on Rubygems with UNION ALL support. Thanks for the PR!

**Pull request closed without merging**
