### PR TITLE
Get GitHub actions running green on 6.0 → 8.0

### PR DESCRIPTION
**Pull request by timdiggins**
Dropping Rails below 6.0.

based on #34

### CODE REVIEW

**Comment by timdiggins** [comment]
This keeps > rails 6.0 and 6.1 -- can also drop all EOL'd rails - but maybe make a last release for them first?

**Comment by timdiggins** [comment]
@glebm 👋  -- Any chance of a review / merge / release ?

**Comment by glebm** [comment]
Merged but I don't have gem release permissions

**Comment by timdiggins** [comment]
@brianhempel can you release?

**Comment by dennispaagman** [comment]
hey everyone, can a version be released with these fixes? The currently published version breaks with Rails 8. Thanks a lot!

edit: also see https://github.com/brianhempel/active_record_union/issues/39

**Pull request merged**
